Setup project
dinosysOrg/sportbook-android pull request #1
Opened 2017-05-17 09:51 UTC by thachnguyendino

Changes:
- Set package name: com.dinosys.sportbook
- Apply Support from API 15 and higher.
- Added library: ButterKnife, Retrofit, RxAndroid, Glide, Gson, Facebook sdk.

2017-05-17 10:57 UTC, ducdino commented
I have reviewed this. @ndduy Please approve this pull request.

2017-05-18 03:06 UTC, ndduy requested changes

2017-05-18 03:06 UTC, ndduy commented on SportBook/.idea/compiler.xml
> +</project>
Please add .idea into git ignore

2017-05-18 03:06 UTC, ndduy commented on SportBook/app/.gitignore
> +/build
We should have 1 gitignore only

2017-05-18 03:06 UTC, ndduy commented on SportBook/.gitignore
> +.externalNativeBuild
Example of gitignore

# Built application files
*.apk
*.ap_

# Files for the Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# idea files
.idea/

*.iml

third_parties/android_dbinspector/

2017-05-18 03:37 UTC, ndduy approved these changes

2017-05-18 03:37 UTC, merged